# Week 4 Homework

### What does one need to do to use a module?
You need to import the module into your program using import "module".  Such as import datetime as dt. This will import the module and you can begin to use it.  


### Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
Math module. 

import math

print("The sum of this list is ", math.fsum([1, 2, 3,]))

This will print: The sum of this list is 6.  

### What is a benefit of using Exception handling?
This allows us to not generate an error from Python that would have made the program crash, instead we can run the code and prevent the error message from occuring.   


### What are the 4 components used for Python Exception Handling?
- The try block that lets you run the block of code for errors.
- The except block that lets you handle the error. 
- The else blck that lets you execute code when there is no error. 
- The finally block that lets you run the code regardless of the results of the try and except blocks. 


### NumPy arrays are like what Python data type?
NumPy Arrays are like lists but require less memory, are faster, and more convenient. 


### What is one of the main benefits of using NumPy arrays.
They require less memory and as a result run faster which can be very beneficial with large data sets.  


### What is one of the main requirements about the 'dtype' of NumPy arrays?
The datatype must be the same.


### Of the 10 uses of NumPy, name 2.
- Arithmetic operations
- Statistical operations


### Name one of the other libraries we'll use with NumPy?
We will use Matplotlib to create data visualizations. 


### What is the shape of NumPy arrays?
The shape is a tuple that specifies the dimensions, length, and size of each array.
For one dimensional arrays it might have the shape of (4) where 4 is the number of elements in an array. 
For two dimensional array it might have the shape of (3,5) where 3 is the number of rows and n is the number of columns. 

### What is a Tensor?
A tensoru is an array with 3 or more dimensions. 


### Name a reason why it's better using NumPy for Data Analysis than using a Python List?
NumPy uses less memory, is faster, and more convenient to work with. 


### When creating an "empty" array, where do the elements come from?
The elements come from the block of memory it allocated. 


In [54]:
#Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name form that variable.
import datetime as dt

currentdate= dt.datetime.now()
print(currentdate)

from datetime import date
today = date.today()
print("Current month is:",today.month)


#Write a simple function that takes 2 parameters -- a first name and a day name.
def myfunction(fname, age):
    print(fname + " Moore ", age)

myfunction(fname = "Ryan", age = 25)


"""Set a default value for the day name of Sunday.
    - Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!".
    Remember to use the variables in the greeting to replace first-name and day-name.
    - Invoke this function with 2 variables.
    - Invoke this function with 1 variable only.
"""
def mysecondfunction(fname, day_name= "Sunday"):
    print(f"Hi {fname}! Happy {day_name}!")

mysecondfunction(fname= "Ryan") 

#invoke this function with 2 variables
def mythirdfunction(fname, day_name):
    print(f"Hi {fname}! Happy {day_name}!")

mythirdfunction(fname = "Ryan", day_name= "Monday")

#invoke this function with 1 variable 
def myfourthfunction(day_name, fname = "Ryan"):
    print(f"Hi {fname}! Happy {day_name}!")

myfourthfunction(day_name = "Sunday")

""" Write a block of code to handle one of the most common Python exception errors. 
Select one of the common errors from the curriculum section on Python Exception handling. 
Have your code example uses the try,except, else, and finally components.
"""
#Print is spelled wrong to provide a Syntax Error in the Try. 
try:
    pritn("This is a try block")
except:
    print("This is an except block")
else:
    print("This is an else block")
finally:
    print("This is a finally block")


#Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
mynumpyarray = np.arange(12).reshape(2, 3, 2)
print("The shape of mynumpyarray is ", mynumpyarray)


#Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

mysecondarray = np.linspace(0, 20, 6)
print(mysecondarray)

#Make a Deep Copy of the above array you created in point #5 above.
import copy
mydeepcopy = copy.deepcopy(mysecondarray)
print(mydeepcopy)


""" 
Using NumPy, 'broadcast' the multiplication of the following 2 arrays below to a 2-D array using the newaxis parameter
- [0.71, 0.1, 0.24, 0.3]
- [0.8, 0.59, 1.0, 1.11]
"""
from numpy import array, newaxis

arrayone = array([0.71, 0.1, 0.24, 0.3])
arraytwo = array([0.8, 0.59, 1.0, 1.11])

print(arrayone[:,newaxis] * arraytwo)



2023-02-20 13:13:51.452188
Current month is: 2
Ryan Moore  25
Hi Ryan! Happy Sunday!
Hi Ryan! Happy Monday!
Hi Ryan! Happy Sunday!
This is an except block
This is a finally block
The shape of mynumpyarray is  [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
[[0.568  0.4189 0.71   0.7881]
 [0.08   0.059  0.1    0.111 ]
 [0.192  0.1416 0.24   0.2664]
 [0.24   0.177  0.3    0.333 ]]
