# Python Homework Week 5


### What does Pandas stand for?

Pandas derived from the word "Panel Data"

### What are the 2 collections used in Pandas?



#### Name 4 things Pandas can do for us.

Pandas can do data visualizations, data cleaning, data inspections, and statistical analysis. 

### To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

The inplace = True key word will update the dataframe to the new change.  

### What is a CSV

A CSV stands for a comma separated value file. 

### When cleaning data what values do we not like in our data?

Null values because these are the wrong result when you analyze data.  

In [184]:
 #Concatenate these 3 arrays into a new array named 'newArray'
import pandas as pd

a1 = pd.DataFrame([[25, 16]])
a2 = pd.DataFrame([[11, 2], [13, 4]])
a3 = pd.DataFrame([[7, 81], [5, 6], [11, 12]])

newArray = pd.concat([a1, a2, a3], axis= 0)
print('This is the new array: \n', newArray, '\n')

#Sort 'newArray' in order into 'sortedArray'

sortedArray = pd.DataFrame(newArray.sort_values(by = [0 , 1]))
print('This is the sorted array: \n', sortedArray,'\n')

# Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = sortedArray.values.reshape(2, 2, 3)
print('This is the reshaped array: \n', reshapedArray,'\n')

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
a = reshapedArray.reshape(4,3)

var1, var2, var3, var4 = a[0], a[1], a[2], a[3]
print('This is var1:',var1,'\n','This is var2:', var2,'\n', 'This is var3:',var3, '\n', 'This is var4:',var4)


This is the new array: 
     0   1
0  25  16
0  11   2
1  13   4
0   7  81
1   5   6
2  11  12 

This is the sorted array: 
     0   1
1   5   6
0   7  81
0  11   2
2  11  12
1  13   4
0  25  16 

This is the reshaped array: 
 [[[ 5  6  7]
  [81 11  2]]

 [[11 12 13]
  [ 4 25 16]]] 

This is var1: [5 6 7] 
 This is var2: [81 11  2] 
 This is var3: [11 12 13] 
 This is var4: [ 4 25 16]


In [260]:
#Combined and sort the following arrays into one called 'comboArray' 
import pandas as pd
import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

a = np.concatenate([one,two,three], axis = 0)


comboArray= np.sort(a)
print(comboArray, '\n')

#Take 'comboArray' and perform the following slicing activities: print sec1 - the 2nd element
sec1 = comboArray[1]
print(sec1, '\n')

#print sec2 - all elements from the 3rd element to the last

sec2 = comboArray[2:]
print(sec2, '\n')

#print sec3 - all elements from the 4th to the 14th elements

sec3 = comboArray[3:14]
print(sec3, '\n')

#print sec4 - the last 6 elements

sec4 = comboArray[-6:]
print(sec4)

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.

sec5 = comboArray[:-10]
print(sec5)

#print sec6 - from #20 every even element to the end

sec6 = comboArray[16::2]
print(sec6)

#print sec7 - from the last element moving forward, every 5th element.

sec7 = comboArray[-1::-5]
print(sec7)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27] 

1 

[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27] 

[ 3  4  5  6  7 10 11 12 13 14 15] 

[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [271]:
#Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
import numpy as np 
from numpy import array, newaxis
import pandas as pd

array1 = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]], [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]], [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array2= array ([[17.0, 70.0, 10.7]])

print(array1[:,newaxis] + array2)

#Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.

print(array1[:,newaxis] - array2)


#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
a = array2[array2 % 3 == 0]
b = array1[array1 % 3 == 0]
divisbleby3 = print(a), print(b)

[[[[ 17.    70.    10.8 ]
   [ 27.    80.3   20.71]]]


 [[[ 37.    90.02  30.8 ]
   [ 47.   101.    41.  ]]]


 [[[ 57.4   94.    50.7 ]
   [ 32.    85.5   36.2 ]]]]
[[[[-17.   -70.   -10.6 ]
   [ -7.   -59.7   -0.69]]]


 [[[  3.   -49.98   9.4 ]
   [ 13.   -39.    19.6 ]]]


 [[[ 23.4  -46.    29.3 ]
   [ -2.   -54.5   14.8 ]]]]
[]
[ 0.  0. 30. 24. 15.]


In [288]:
#Using Series, create a DataFrame that looks like this:
import pandas as pd 
s1 = pd.Series(['flour','milk','eggs','spam'], name = 'Ingredients')
s2 = pd.Series([4, 1, 2, 1], name = 'Quantity') 
s3= pd.Series(['cups', 'cup','large', 'can'], name = 'Unit')

dataframe1 = pd.concat([s1,s2,s3], axis=1)
print(dataframe1)

  Ingredients  Quantity   Unit
0       flour         4   cups
1        milk         1    cup
2        eggs         2  large
3        spam         1    can


In [3]:
#Take this data and create a DataFrame named studentData
import pandas as pd
data={'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
      'Height': [5.1, 6.2, 5.1, 5.2],
      'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
      'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
      'Age': [21, 23, 24, 21],
      'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
      'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}
studentData=pd.DataFrame(data)
print(studentData)

#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Deserts']= deserts
print(studentData)

#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by= ['Name', 'address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  
      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot        

In [4]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

#(A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

Veggies = pd.DataFrame({'Tomato':[1,2], 'Cucumber':[2,5], 'Carrot':[3,4]}, index =['Produce #', 'Taste'])
print (Veggies)

Veggies.to_csv('Veggie.csv')
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
Peppers = [4, 5]
Veggies['Peppers'] = Peppers

print(Veggies)
Veggies.to_csv('Veggieseditted.csv')

           Tomato  Cucumber  Carrot
Produce #       1         2       3
Taste           2         5       4
           Tomato  Cucumber  Carrot  Peppers
Produce #       1         2       3        4
Taste           2         5       4        5
